[package]
name = "rust-wavetable-synth"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.17.3"
clap = { version = "4.4.17", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
